// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// disc_cdf_from_quantiles
NumericVector disc_cdf_from_quantiles(const NumericVector& quantiles, const NumericVector& values, const int k_max, const int k_min);
RcppExport SEXP _xflex4cast_disc_cdf_from_quantiles(SEXP quantilesSEXP, SEXP valuesSEXP, SEXP k_maxSEXP, SEXP k_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type quantiles(quantilesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const int >::type k_max(k_maxSEXP);
    Rcpp::traits::input_parameter< const int >::type k_min(k_minSEXP);
    rcpp_result_gen = Rcpp::wrap(disc_cdf_from_quantiles(quantiles, values, k_max, k_min));
    return rcpp_result_gen;
END_RCPP
}
// rdisc_from_cdf
IntegerVector rdisc_from_cdf(const IntegerVector& support, const NumericVector& cdf, double total_mass, int n);
RcppExport SEXP _xflex4cast_rdisc_from_cdf(SEXP supportSEXP, SEXP cdfSEXP, SEXP total_massSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type support(supportSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type cdf(cdfSEXP);
    Rcpp::traits::input_parameter< double >::type total_mass(total_massSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rdisc_from_cdf(support, cdf, total_mass, n));
    return rcpp_result_gen;
END_RCPP
}
// rdisc_from_quantile_matrix
IntegerMatrix rdisc_from_quantile_matrix(const NumericMatrix& value_mat, const NumericVector& quantiles, const int n_samples);
RcppExport SEXP _xflex4cast_rdisc_from_quantile_matrix(SEXP value_matSEXP, SEXP quantilesSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type value_mat(value_matSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type quantiles(quantilesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(rdisc_from_quantile_matrix(value_mat, quantiles, n_samples));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xflex4cast_disc_cdf_from_quantiles", (DL_FUNC) &_xflex4cast_disc_cdf_from_quantiles, 4},
    {"_xflex4cast_rdisc_from_cdf", (DL_FUNC) &_xflex4cast_rdisc_from_cdf, 4},
    {"_xflex4cast_rdisc_from_quantile_matrix", (DL_FUNC) &_xflex4cast_rdisc_from_quantile_matrix, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_xflex4cast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
