# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

disc_cdf_from_quantiles <- function(quantiles, values, k_max, k_min) {
    .Call(`_xflex4cast_disc_cdf_from_quantiles`, quantiles, values, k_max, k_min)
}

rdisc_from_cdf <- function(support, cdf, total_mass, n) {
    .Call(`_xflex4cast_rdisc_from_cdf`, support, cdf, total_mass, n)
}

rdisc_from_quantile_matrix <- function(value_mat, quantiles, n_samples) {
    .Call(`_xflex4cast_rdisc_from_quantile_matrix`, value_mat, quantiles, n_samples)
}

